// tests/demo/locators/signupPageLocators.ts
export const locators = {
  homePageLogo: "//img[@alt='Website for automation practice']",
  signupLoginBtn: "//a[normalize-space()='Signup / Login']",
  newUserSignupText: "//h2[normalize-space()='New User Signup!']",
  nameInput: "//input[@placeholder='Name']",
  emailInput: "//input[@data-qa='signup-email']",
  signupBtn: "//button[normalize-space()='Signup']",
  enterAccountInfo: "//b[normalize-space()='Enter Account Information']",
  titleCheckbox: "//input[@value='Mr']",
  passwordInput: "//input[@id='password']",
  dobDay: "//select[@id='days']",
  dobMonth: "//select[@id='months']",
  dobYear: "//select[@id='years']",
  newsletterCheckbox: "//input[@id='newsletter']",
  firstNameInput: "//input[@id='first_name']",
  lastNameInput: "//input[@id='last_name']",
  addressInput: "//input[@id='address1']",
  countrySelect: "//select[@id='country']",
  stateInput: "//input[@id='state']",
  cityInput: "//input[@id='city']",
  zipcodeInput: "//input[@id='zipcode']",
  mobileNumberInput: "//input[@id='mobile_number']",
  createAccountBtn: "//button[normalize-space()='Create Account']",
  accountCreatedText: "//b[normalize-space()='Account Created!']",
  continueBtn: "//a[normalize-space()='Continue']",
  loggedInAsText: "//li[10]//a[1]",
  logOutBtn: "//a[normalize-space()='Logout']",
  accountLogoutText: "//h2[normalize-space()='Login to your account']",
  emailAlreadyExistsError: "//p[contains(text(), 'Email Address already exist')]",
};
